apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  containers:
  - args:
    - npm
    - run
    - docker
    image: app
    name: express-authservice
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}