apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\JiriHusak\Development\kompose.exe --provider openshift --file
      docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
