apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\JiriHusak\Development\kompose.exe --provider openshift --file
      docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: openldap
  name: openldap
spec:
  ports:
  - name: "8389"
    port: 8389
    targetPort: 389
  - name: "8636"
    port: 8636
    targetPort: 636
  selector:
    io.kompose.service: openldap
status:
  loadBalancer: {}
