apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: openldap
  name: openldap
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
#      name: osixia/openldap:latest
      name: docker.io/jhusak/anatldap
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
